name: Build .deb
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_deb:
    runs-on: ubuntu-latest
    container: ghcr.io/educorvi/ubuntu_packaging:devcontainer
    steps:
      - uses: actions/checkout@v3
      - name: Build .deb
        working-directory: backend
        run: make deb
      - uses: actions/upload-artifact@v3
        with:
          name: deb-file
          path: backend/deb_dist/*.deb